### ISSUE TITLE
how to work without qooxxdoo?

### ISSUE THREAD

**Issue by huoying7080** [MurphyMc/poxdesk#1]
if i don't need qooxxdoo,how to configure poxdesk
openflow@openflowtutorial:~/pox/ext/poxdesk/poxdesk$ ./generate.py
Cannot find real generator script under: "/home/openflow/pox/ext/poxdesk/qx/tool/bin/generator.py"; aborting

**Comment by MurphyMc** [comment]
If I have remembered to push the current version of the generated code, I think that step can just be skipped.

You're probably better off directing future questions about POXDesk to the pox-dev mailing list: http://www.noxrepo.org/community/mailing-lists/
