### ISSUE TITLE
poxdesk appears to freeze?

### ISSUE THREAD

**Issue by colin-scott** [MurphyMc/poxdesk#4]
On the latest version of POX:

```
$ ./pox.py poxdesk
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
WARNING:core:Still waiting on 2 component(s)
INFO:core:POX 0.2.0 (carp) is up.
```

Is there something more I need to do to bring the GUI up?

**Comment by MurphyMc** [comment]
If you run at debug log level, you can see which components it's waiting on.

It's probably answered by looking at the Getting Started on the wiki, though:
https://github.com/MurphyMc/poxdesk/wiki/Getting-Started

**Comment by MurphyMc** [comment]
Assuming this worked. :)
