### ISSUE TITLE
Not able to view topology on windows.

### ISSUE THREAD

**Issue by nikhildahake** [MurphyMc/poxdesk#6]
1) I am started mininet on Ubuntu VM using this command: 

sudo mn --topo single,48 --mac --controller=remote,ip=192.168.56.1,port=6633

2) I started pox with poxdesk on 'WINDOWS 10' like this:

pox.py samples.pretty_log web messenger messenger.log_service messenger.ajax_transport openflow.of_service poxdesk openflow.discovery poxdesk.tinytopo pox.forwarding.hub

3) I am able to run 'pingall' command on mininet successfully.

4) I navigate to http://127.0.0.1:8000/poxdesk/source/ and try to open my topoviewer and it comes up blank. See image here:
https://pasteboard.co/JrD1UY8.png

My question: "Is Topo Viewer supposed to work on windows?"

**Comment by nikhildahake** [comment]
Hi Murphy -- I tried the same above commands in Ubuntu and still could not see the topology. What am I doing wrong here?

**Comment by MurphyMc** [comment]
I think this may be the expected result.  I think tinytopo only shows switches, not hosts.  And I believe your topology only has a single switch -- which is showing up.

**Comment by nikhildahake** [comment]
@MurphyMc  -- Okay, cool. Is there anyway I can see links and nodes as well? Are there any other topo viewers that I can use out of the box like tiny topo? 

Thanks!

**Comment by MurphyMc** [comment]
To be clear, it shows links and nodes -- just only switch nodes, not hosts.  We get direct knowledge about switches out of OpenFlow, and discovery figures out the links between them.  With hosts, it's all just guesswork -- we don't get explicit information about them.

POX has the host_tracker component which tries to do this guessing for you.  It wouldn't be hard to modify tinytopo to consume the host_tracker events and add them to the graph, but nobody has ever bothered.

POX's misc.gephi_topo component does exactly this, though.  A potential downside is that it requires Gephi (which, unfortunately, does not seem to get much love these days).  But even if one didn't one to use Gephi, one could look at the gephi_topo code to get an idea of how to add host information to tinytopo.

**Comment by nikhildahake** [comment]
@MurphyMc  -- Okay, thanks for all the information! I'll research into it. Thanks.
